<?php
/**
 * Plugin Name: Advanced Variable Options
 * Description: Attribute image galleries, image swatches, and size availability controls for WooCommerce variable products.
 * Version: 0.2.0
 * Author: Jv Secate
 * Requires Plugins: woocommerce
 * Text Domain: advanced-variable-options
 * Requires at least: 6.0
 * Requires PHP: 8.0
 */

if (!defined('ABSPATH')) {
    exit;
}

// Comments and some strings were generated by LLMs.

class AVO_Advanced_Variable_Options {
    const META_KEY = '_avo_attribute_galleries';
    const VERSION = '0.2.0';

    public function __construct() {
        add_filter('woocommerce_product_data_tabs', [$this, 'add_product_tab']);
        add_action('woocommerce_product_data_panels', [$this, 'render_product_panel']);
        add_action('woocommerce_admin_process_product_object', [$this, 'save_product_fields']);
        add_action('admin_enqueue_scripts', [$this, 'enqueue_admin_assets']);
        add_action('wp_enqueue_scripts', [$this, 'enqueue_frontend_assets']);
    }

    public function add_product_tab($tabs) {
        $tabs['avo_attribute_galleries'] = [
            'label'    => __('Attribute Galleries', 'advanced-variable-options'),
            'target'   => 'avo_attribute_galleries_panel',
            'class'    => ['show_if_variable'],
            'priority' => 80,
        ];
        return $tabs;
    }

    public function render_product_panel() {
        global $post;
        if (!$post || $post->post_type !== 'product') {
            return;
        }

        $product = wc_get_product($post->ID);
        if (!$product) {
            return;
        }

        $saved = get_post_meta($post->ID, self::META_KEY, true);
        $saved = is_array($saved) ? $saved : [];
        $attributes = avo_get_product_attribute_options($product);
        ?>
        <div id="avo_attribute_galleries_panel" class="panel woocommerce_options_panel hidden">
            <div class="options_group">
                <p style="padding: 0 12px;">
                    <?php esc_html_e('Add image galleries to any available product attribute option. Example: Color > Black can have multiple images, but this also works for material, texture, model, or any custom attribute.', 'advanced-variable-options'); ?>
                </p>

                <?php if (empty($attributes)) : ?>
                    <p style="padding: 0 12px;">
                        <?php esc_html_e('No variable attributes found. Add attributes to the product, enable "Used for variations", save the product, then return here.', 'advanced-variable-options'); ?>
                    </p>
                <?php endif; ?>

                <?php wp_nonce_field('avo_save_attribute_galleries', 'avo_attribute_galleries_nonce'); ?>

                <?php foreach ($attributes as $attribute_key => $attribute) : ?>
                    <div class="avo-attribute-group" style="border-top:1px solid #ddd; padding:12px;">
                        <h3 style="margin:0 0 12px;"><?php echo esc_html($attribute['label']); ?> <code><?php echo esc_html($attribute_key); ?></code></h3>
                        <?php foreach ($attribute['options'] as $option) :
                            $option_slug = $option['slug'];
                            $image_ids = isset($saved[$attribute_key][$option_slug]) && is_array($saved[$attribute_key][$option_slug]) ? $saved[$attribute_key][$option_slug] : [];
                            $image_ids_string = implode(',', array_map('absint', $image_ids));
                            ?>
                            <div class="form-field avo-gallery-field" style="padding: 10px 0; border-top:1px solid #f0f0f0;">
                                <label style="display:block; margin-bottom: 8px;">
                                    <strong><?php echo esc_html($option['label']); ?></strong>
                                    <code><?php echo esc_html($option_slug); ?></code>
                                </label>
                                <input type="hidden" class="avo-gallery-ids" name="avo_attribute_galleries[<?php echo esc_attr($attribute_key); ?>][<?php echo esc_attr($option_slug); ?>]" value="<?php echo esc_attr($image_ids_string); ?>" />
                                <button type="button" class="button avo-select-gallery"><?php esc_html_e('Select images', 'advanced-variable-options'); ?></button>
                                <button type="button" class="button avo-clear-gallery"><?php esc_html_e('Clear', 'advanced-variable-options'); ?></button>
                                <div class="avo-gallery-preview" style="margin-top: 10px; display: flex; gap: 6px; flex-wrap: wrap;">
                                    <?php foreach ($image_ids as $image_id) : ?>
                                        <?php echo wp_get_attachment_image((int) $image_id, 'thumbnail', false, ['style' => 'width:60px;height:60px;object-fit:cover;border:1px solid #ddd;']); ?>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php
    }

    public function save_product_fields($product) {
        if (!isset($_POST['avo_attribute_galleries_nonce']) || !wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['avo_attribute_galleries_nonce'])), 'avo_save_attribute_galleries')) {
            return;
        }

        if (!isset($_POST['avo_attribute_galleries']) || !is_array($_POST['avo_attribute_galleries'])) {
            delete_post_meta($product->get_id(), self::META_KEY);
            return;
        }

        $clean = [];
        foreach ($_POST['avo_attribute_galleries'] as $attribute_key => $options) {
            if (!is_array($options)) {
                continue;
            }
            $attribute_key = avo_clean_attribute_key($attribute_key);
            foreach ($options as $option_slug => $image_ids_string) {
                $option_slug = sanitize_title($option_slug);
                $image_ids_string = sanitize_text_field(wp_unslash($image_ids_string));
                $image_ids = array_values(array_filter(array_map('absint', explode(',', $image_ids_string))));
                if (!empty($image_ids)) {
                    $clean[$attribute_key][$option_slug] = $image_ids;
                }
            }
        }

        if (empty($clean)) {
            delete_post_meta($product->get_id(), self::META_KEY);
        } else {
            update_post_meta($product->get_id(), self::META_KEY, $clean);
        }
    }

    public function enqueue_admin_assets($hook) {
        global $post;
        if (($hook !== 'post.php' && $hook !== 'post-new.php') || !$post || $post->post_type !== 'product') {
            return;
        }
        wp_enqueue_media();
        wp_enqueue_style('avo-admin', plugin_dir_url(__FILE__) . 'assets/admin.css', [], self::VERSION);
        wp_enqueue_script('avo-admin', plugin_dir_url(__FILE__) . 'assets/admin.js', ['jquery'], self::VERSION, true);
        wp_localize_script(
            'avo-admin',
            'avoAdmin',
            [
                'frameTitle' => __('Select attribute gallery images', 'advanced-variable-options'),
                'frameButton' => __('Use selected images', 'advanced-variable-options'),
            ]
        );
    }

    public function enqueue_frontend_assets() {
        if (!class_exists('WooCommerce')) {
            return;
        }
        wp_enqueue_style('avo-frontend', plugin_dir_url(__FILE__) . 'assets/frontend.css', [], self::VERSION);
        wp_enqueue_script('avo-frontend', plugin_dir_url(__FILE__) . 'assets/frontend.js', ['jquery'], self::VERSION, true);
    }
}

function avo_clean_attribute_key($key) {
    $key = preg_replace('/^attribute_/', '', (string) $key);
    return sanitize_title($key);
}

function avo_normalize_variation_attribute_key($key) {
    return 'attribute_' . avo_clean_attribute_key($key);
}

function avo_attribute_search_text($attribute_key) {
    $raw = avo_clean_attribute_key($attribute_key);
    $label = function_exists('wc_attribute_label') ? wc_attribute_label($raw) : $raw;
    return strtolower(remove_accents($raw . ' ' . $label));
}

function avo_variation_label($attribute_key, $value, $fallback = '') {
    $value = (string) $value;
    if ($value === '') {
        return $fallback ?: __('Product option', 'advanced-variable-options');
    }
    $taxonomy = avo_clean_attribute_key($attribute_key);
    if (taxonomy_exists($taxonomy)) {
        $term = get_term_by('slug', $value, $taxonomy);
        if ($term && !is_wp_error($term)) {
            return $term->name;
        }
    }
    return ucwords(str_replace(['-', '_'], ' ', $value));
}

function avo_get_product_attribute_options($product) {
    if (!$product instanceof WC_Product) {
        return [];
    }

    $result = [];

    // Admin galleries are intentionally based on every product attribute, not
    // only Color/Cor and not only attributes already detected as variation
    // attributes. This makes the plugin useful for imports where the visual
    // selector is named Material, Modelo, Textura, or a custom attribute.
    foreach ($product->get_attributes() as $attribute_key => $attribute) {
        if (!$attribute instanceof WC_Product_Attribute) {
            continue;
        }

        $clean_key = avo_clean_attribute_key($attribute->get_name());
        $options = [];

        if ($attribute->is_taxonomy()) {
            $terms = wc_get_product_terms($product->get_id(), $attribute->get_name(), ['fields' => 'all']);
            foreach ($terms as $term) {
                if (!$term || is_wp_error($term)) {
                    continue;
                }
                $options[$term->slug] = [
                    'slug'  => $term->slug,
                    'label' => $term->name,
                ];
            }
        } else {
            foreach ((array) $attribute->get_options() as $value) {
                if ($value === '') {
                    continue;
                }
                $slug = sanitize_title($value);
                $options[$slug] = [
                    'slug'  => $slug,
                    'label' => ucwords(str_replace(['-', '_'], ' ', $value)),
                ];
            }
        }

        if (!empty($options)) {
            $result[$clean_key] = [
                'label'   => wc_attribute_label($attribute->get_name()),
                'options' => array_values($options),
            ];
        }
    }

    return $result;
}

function avo_get_attribute_galleries($product_id) {
    $saved = get_post_meta($product_id, AVO_Advanced_Variable_Options::META_KEY, true);
    return is_array($saved) ? $saved : [];
}

function avo_get_gallery_for_attribute_value($product_id, $attribute_key, $value) {
    $galleries = avo_get_attribute_galleries($product_id);
    $attribute_key = avo_clean_attribute_key($attribute_key);
    $value = sanitize_title($value);
    return isset($galleries[$attribute_key][$value]) && is_array($galleries[$attribute_key][$value]) ? array_values(array_map('absint', $galleries[$attribute_key][$value])) : [];
}

function avo_get_visual_attribute_needles() {
    return (array) apply_filters(
        'avo_visual_attribute_needles',
        ['color', 'colour', 'cor', 'texture', 'textura', 'estampa', 'modelo', 'model', 'material']
    );
}

function avo_get_size_attribute_needles() {
    return (array) apply_filters(
        'avo_size_attribute_needles',
        ['size', 'tamanho', 'numero', 'numeracao', 'number', 'calce']
    );
}

function avo_detect_visual_attribute_key($product) {
    if (!$product instanceof WC_Product || !$product->is_type('variable')) {
        return '';
    }

    $attributes = $product->get_variation_attributes();
    $galleries = avo_get_attribute_galleries($product->get_id());

    // Prefer the first attribute that actually has a saved gallery. This fixes imports
    // where the color attribute is not named Color/Cor.
    foreach (array_keys((array) $attributes) as $key) {
        $clean = avo_clean_attribute_key($key);
        if (!empty($galleries[$clean])) {
            return $clean;
        }
    }

    $needles = avo_get_visual_attribute_needles();
    foreach (array_keys((array) $attributes) as $key) {
        $haystack = avo_attribute_search_text($key);
        foreach ($needles as $needle) {
            if (strpos($haystack, $needle) !== false) {
                return avo_clean_attribute_key($key);
            }
        }
    }

    foreach ((array) $attributes as $key => $values) {
        $sample_values = array_filter((array) $values);
        if (empty($sample_values)) {
            continue;
        }
        $numeric_count = 0;
        foreach ($sample_values as $value) {
            if (preg_match('/^\d{1,2}([.,]\d)?$/', (string) $value)) {
                $numeric_count++;
            }
        }
        if ($numeric_count < count($sample_values)) {
            return avo_clean_attribute_key($key);
        }
    }
    return '';
}

function avo_detect_size_attribute_key($product) {
    if (!$product instanceof WC_Product || !$product->is_type('variable')) {
        return '';
    }
    $needles = avo_get_size_attribute_needles();
    $attributes = $product->get_variation_attributes();
    $visual_key = avo_detect_visual_attribute_key($product);
    foreach (array_keys((array) $attributes) as $key) {
        $haystack = avo_attribute_search_text($key);
        foreach ($needles as $needle) {
            if (strpos($haystack, $needle) !== false) {
                return avo_clean_attribute_key($key);
            }
        }
    }
    foreach (array_keys((array) $attributes) as $key) {
        $clean = avo_clean_attribute_key($key);
        if (!$visual_key || sanitize_title($clean) !== sanitize_title($visual_key)) {
            return $clean;
        }
    }
    return '';
}

function avo_get_all_variation_data($product) {
    if (!$product instanceof WC_Product || !$product->is_type('variable')) {
        return [];
    }
    $data = [];
    foreach ($product->get_children() as $variation_id) {
        $variation_product = wc_get_product($variation_id);
        if (!$variation_product instanceof WC_Product_Variation) {
            continue;
        }
        $attributes = [];
        foreach ($variation_product->get_attributes() as $attribute_key => $attribute_value) {
            if ($attribute_value === '') {
                continue;
            }
            $attributes[avo_normalize_variation_attribute_key($attribute_key)] = sanitize_title($attribute_value);
        }
        $image_id = $variation_product->get_image_id() ?: $product->get_image_id();
        $data[] = [
            'variation_id' => $variation_product->get_id(),
            'attributes'   => $attributes,
            'image_id'     => $image_id ? absint($image_id) : 0,
            'is_in_stock'  => $variation_product->is_in_stock(),
        ];
    }
    return $data;
}

function avo_variation_query_args($variation) {
    $query_args = [];
    foreach ((array) ($variation['attributes'] ?? []) as $key => $value) {
        if ($value !== '') {
            $query_args[avo_normalize_variation_attribute_key($key)] = sanitize_title($value);
        }
    }
    if (!empty($variation['variation_id'])) {
        $query_args['variation_id'] = absint($variation['variation_id']);
    }
    return $query_args;
}

function avo_get_product_gallery_items($product) {
    if (!$product instanceof WC_Product) {
        return [];
    }

    $items = [];
    $add_item = function ($image_id, $visual_attr = '', $visual_value = '', $source = 'product') use (&$items) {
        $image_id = absint($image_id);
        if (!$image_id) {
            return;
        }

        $visual_attr = $visual_attr ? avo_normalize_variation_attribute_key($visual_attr) : '';
        $visual_value = $visual_value ? sanitize_title($visual_value) : '';
        $key = implode('|', [$image_id, $visual_attr, $visual_value]);

        if (!isset($items[$key])) {
            $items[$key] = [
                'image_id'     => $image_id,
                'visual_attr'  => $visual_attr,
                'visual_value' => $visual_value,
                'source'       => sanitize_key($source),
            ];
        }
    };

    $add_item($product->get_image_id(), '', '', 'product');

    foreach ($product->get_gallery_image_ids() as $image_id) {
        $add_item($image_id, '', '', 'product_gallery');
    }

    if ($product->is_type('variable')) {
        $visual_key = avo_detect_visual_attribute_key($product);
        $visual_attr = $visual_key ? avo_normalize_variation_attribute_key($visual_key) : '';

        if ($visual_key) {
            foreach (avo_get_attribute_galleries($product->get_id()) as $attribute_key => $attribute_galleries) {
                if (avo_clean_attribute_key($attribute_key) !== avo_clean_attribute_key($visual_key)) {
                    continue;
                }

                foreach ((array) $attribute_galleries as $visual_value => $ids) {
                    foreach ((array) $ids as $image_id) {
                        $add_item($image_id, $visual_attr, $visual_value, 'attribute_gallery');
                    }
                }
            }
        }

        foreach ($product->get_children() as $variation_id) {
            $variation_product = wc_get_product($variation_id);
            if (!$variation_product instanceof WC_Product_Variation || !$variation_product->get_image_id()) {
                continue;
            }

            $visual_value = '';
            if ($visual_attr) {
                foreach ($variation_product->get_attributes() as $attribute_key => $attribute_value) {
                    if (avo_normalize_variation_attribute_key($attribute_key) === $visual_attr) {
                        $visual_value = sanitize_title($attribute_value);
                        break;
                    }
                }
            }

            $add_item($variation_product->get_image_id(), $visual_attr, $visual_value, 'variation');
        }
    }

    return array_values($items);
}

function avo_get_visual_variation_swatches($product, $context = 'card') {
    if (!$product instanceof WC_Product || !$product->is_type('variable')) {
        return [];
    }
    $visual_key = avo_detect_visual_attribute_key($product);
    $visual_attr = $visual_key ? avo_normalize_variation_attribute_key($visual_key) : '';
    $variations = avo_get_all_variation_data($product);
    $items = [];

    foreach ($variations as $variation) {
        $attributes = isset($variation['attributes']) && is_array($variation['attributes']) ? $variation['attributes'] : [];
        $visual_value = ($visual_attr && isset($attributes[$visual_attr]) && $attributes[$visual_attr] !== '') ? sanitize_title($attributes[$visual_attr]) : '';
        if (!$visual_value) {
            continue;
        }

        $gallery_ids = avo_get_gallery_for_attribute_value($product->get_id(), $visual_key, $visual_value);
        $display_image_id = !empty($gallery_ids) ? absint($gallery_ids[0]) : absint($variation['image_id'] ?? 0);
        if (!$display_image_id) {
            continue;
        }

        $image = wp_get_attachment_image_url($display_image_id, 'woocommerce_single');
        $thumb = wp_get_attachment_image_url($display_image_id, 'thumbnail');
        if (!$image || !$thumb) {
            continue;
        }

        $candidate = [
            'variation_id' => absint($variation['variation_id'] ?? 0),
            'attributes'   => [$visual_attr => $visual_value],
            'image'        => $image,
            'thumb'        => $thumb,
            'label'        => avo_variation_label($visual_key, $visual_value),
            'value'        => $visual_value,
            'attribute'    => $visual_attr,
            'is_in_stock'  => !empty($variation['is_in_stock']),
            'query_args'   => avo_variation_query_args(['variation_id' => $variation['variation_id'] ?? 0, 'attributes' => [$visual_attr => $visual_value]]),
        ];

        if (!isset($items[$visual_value]) || (!$items[$visual_value]['is_in_stock'] && $candidate['is_in_stock'])) {
            $items[$visual_value] = $candidate;
        }
    }

    return array_values($items);
}

function avo_render_product_option_swatches($product, $context = 'card') {
    $swatches = avo_get_visual_variation_swatches($product, $context);
    if (empty($swatches)) {
        return;
    }
    $classes = 'avo-product-swatches avo-product-swatches--' . sanitize_html_class($context);
    $label = !empty($swatches[0]['attribute']) ? wc_attribute_label(avo_clean_attribute_key($swatches[0]['attribute'])) : __('Product options', 'advanced-variable-options');
    echo '<div class="' . esc_attr($classes) . '" data-avo-label="' . esc_attr($label) . '" aria-label="' . esc_attr__('Product options', 'advanced-variable-options') . '">';
    foreach ($swatches as $index => $swatch) {
        $url = add_query_arg($swatch['query_args'], get_permalink($product->get_id()));
        $tag = $context === 'card' ? 'a' : 'button';
        $attributes = [
            'class'                         => 'avo-product-swatch' . ($index === 0 ? ' is-selected' : ''),
            'data-avo-swatch-image'        => esc_url($swatch['image']),
            'data-avo-variation-attributes'=> esc_attr(wp_json_encode($swatch['attributes'])),
            'data-avo-variation-id'        => absint($swatch['variation_id']),
            'data-avo-visual-value'        => esc_attr($swatch['value']),
            'data-avo-visual-attribute'    => esc_attr($swatch['attribute']),
            'aria-label'                   => esc_attr($swatch['label']),
            'aria-pressed'                 => $index === 0 ? 'true' : 'false',
        ];

        if ($context === 'card') {
            $attributes['href'] = esc_url($url);
        } else {
            $attributes['type'] = 'button';
        }

        $attribute_html = '';
        foreach ($attributes as $name => $value) {
            $attribute_html .= ' ' . esc_attr($name) . '="' . $value . '"';
        }

        printf(
            '<%1$s%2$s><img src="%3$s" alt="%4$s" loading="lazy"></%1$s>',
            tag_escape($tag),
            $attribute_html,
            esc_url($swatch['thumb']),
            esc_attr($swatch['label'])
        );
    }
    echo '</div>';
}

function avo_render_product_gallery_thumbnails($product) {
    if (!$product instanceof WC_Product) {
        return;
    }
    $items = avo_get_product_gallery_items($product);
    if (count($items) < 2) {
        return;
    }
    echo '<div class="avo-gallery-thumbs" aria-label="' . esc_attr__('Product gallery thumbnails', 'advanced-variable-options') . '">';
    foreach ($items as $index => $item) {
        $image_id = absint($item['image_id'] ?? 0);
        $single = wp_get_attachment_image_url($image_id, 'woocommerce_single');
        $full = wp_get_attachment_image_url($image_id, 'full');
        if (!$single || !$full) {
            continue;
        }
        echo '<button type="button" class="avo-gallery-thumb' . ($index === 0 ? ' is-selected' : '') . '" data-avo-gallery-image="' . esc_url($single) . '" data-avo-gallery-full="' . esc_url($full) . '" data-avo-gallery-visual-attribute="' . esc_attr($item['visual_attr'] ?? '') . '" data-avo-gallery-visual-value="' . esc_attr($item['visual_value'] ?? '') . '" data-avo-gallery-source="' . esc_attr($item['source'] ?? '') . '">';
        echo wp_get_attachment_image($image_id, 'thumbnail', false, ['loading' => 'lazy']);
        echo '</button>';
    }
    echo '</div>';
}

function avo_render_product_size_availability($product) {
    if (!$product instanceof WC_Product || !$product->is_type('variable')) {
        return;
    }
    $size_key = avo_detect_size_attribute_key($product);
    if (!$size_key) {
        return;
    }
    $visual_key = avo_detect_visual_attribute_key($product);
    $visual_attr = $visual_key ? avo_normalize_variation_attribute_key($visual_key) : '';
    $size_attr = avo_normalize_variation_attribute_key($size_key);
    $all_sizes = [];
    $size_map = ['all' => []];

    foreach (avo_get_all_variation_data($product) as $variation) {
        $attributes = (array) ($variation['attributes'] ?? []);
        if (empty($attributes[$size_attr])) {
            continue;
        }
        $size_value = sanitize_title($attributes[$size_attr]);
        $visual_value = ($visual_attr && !empty($attributes[$visual_attr])) ? sanitize_title($attributes[$visual_attr]) : 'all';
        $all_sizes[$size_value] = avo_variation_label($size_key, $size_value);
        if (!isset($size_map[$visual_value])) {
            $size_map[$visual_value] = [];
        }
        if (!empty($variation['is_in_stock'])) {
            $size_map[$visual_value][$size_value] = true;
            $size_map['all'][$size_value] = true;
        }
    }

    if (empty($all_sizes)) {
        return;
    }
    natcasesort($all_sizes);
    echo '<div class="avo-size-options" data-avo-size-options data-avo-size-attribute="' . esc_attr($size_attr) . '" data-avo-size-map="' . esc_attr(wp_json_encode($size_map)) . '">';
    echo '<h3 class="avo-option-label">' . esc_html__('Size', 'advanced-variable-options') . '</h3>';
    echo '<div class="avo-size-list">';
    foreach ($all_sizes as $value => $label) {
        $available = !empty($size_map['all'][$value]);
        echo '<button type="button" class="avo-size-option' . (!$available ? ' is-unavailable' : '') . '" data-avo-size-value="' . esc_attr($value) . '" aria-disabled="' . ($available ? 'false' : 'true') . '">' . esc_html($label) . '</button>';
    }
    echo '</div></div>';
}

add_action('plugins_loaded', function () {
    if (class_exists('WooCommerce')) {
        new AVO_Advanced_Variable_Options();
    }
});
